name: Tests Rails 7
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./test/VanillaNestedTestRails7

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.7
          - "3.0"
          - 3.1
          - 3.2

    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          working-directory: test/VanillaNestedTestRails7
          bundler-cache: true
      - name: Unit tests
        run: bundle exec rails test
      - name: System tests
        run: bundle exec rails test:system
