name: Tests Rails 6
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./test/VanillaNestedTests

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.6
          working-directory: test/VanillaNestedTests
          bundler-cache: true
      - name: YARN
        uses: bahmutov/npm-install@v1
        with:
          working-directory: test/VanillaNestedTests
      - name: Unit tests
        run: bundle exec rails test
      - name: System tests
        run: bundle exec rails test:system
